### PR TITLE
Return to edit page after edit.

### PR DESCRIPTION
**Pull request by justinlittman**
## Why was this change made? 🤔
Current behavior drives me crazy.

## How was this change tested? 🤨

⚡ ⚠ If this change involves consuming from other services or writing to shared file systems, test that web archive seed and crawl accessioning (and maybe even SWAP system?) works properly in [stage|qa] environment, in addition to specs. ⚡
QA

### CODE REVIEW

**Comment by justinlittman** [comment]
@lwrubel Assigning to you for consideration of the proposed change.

**Review by jcoyne — COMMENTED** [review]
I think this is sort of a UI anti-pattern, because you see a message that it was updated, then you make more changes, and the message "Collection updated" is still there.  It's not clear to the user that they need to click save again unless you make the message disappear once they've changed something.

**Comment by lwrubel** [comment]
Spelling this out since the PR title didn't fully explain what the changes are:
1. When you create a new collection, you now stay on the edit page, rather than get returned to the index. You get a notice that says "Collection created." And then if you edit it, you get the "Collection updated" notice. 
2. When you click on the "Queue fetch jobs" the redirect changes so that now you stay on the Edit page rather than getting redirected to the collections index. 

These both make sense to me. @apchan could you give this a thumbs up if you agree?

The anti-pattern that @jcoyne is pointing out seems to already be there, if I am understanding correctly. @justinlittman if I am misunderstanding the change on edit, let me know. Depending on this, I will set up a new issue to discuss how to improve the edit/update UI.

**Comment by jcoyne** [comment]
The anti pattern doesn't exist at present, because you don't get redirected to the edit page on update presently.

**Comment by lwrubel** [comment]
OK, now I understand where I misunderstood the current behavior (had not been looking at a deploy of main to compare with current behavior). Thanks, @jcoyne and @justinlittman. 

It seems like as we are adding more features to the app it would be useful to have a show (detail) page with an Edit button. And then we could follow a normal pattern for redirect on update.

**Pull request closed without merging**
