### PR TITLE
Add provider and account to collection list page.

### LINKED ISSUE #127: Add wasapi_provider and wasapi_account to collection list

### PR DESCRIPTION
**Pull request by justinlittman**
closes #127

### CODE REVIEW

**Comment by justinlittman** [comment]
I'm meh about testing normal page display. It seems like an infinite task with little return. And, in general, our coverage is spotty anyway.

But as the reviewer, I defer to your judgment.

**Comment by mjgiarlo** [comment]
> I'm meh about testing normal page display. It seems like an infinite task with little return. And, in general, our coverage is spotty anyway.
> 
> But as the reviewer, I defer to your judgment.

I welcome comments from other @sul-dlss/infrastructure-team folks here re: what our expectations are.

**Comment by jcoyne** [comment]
I don't think this needs it as it's simply displaying values from a model, with no calculations or anything.  I think it's overkill to test for something as simple as this, especially as there are tests that draw this page (so there are no overt errors)

**Pull request merged**
