### PR TITLE
Improved date picker.

### LINKED ISSUE #88: Improve fetch_start_month date picker
Since this is supposed to be the start month, this should only allow the user to select a year and month. See https://stackoverflow.com/questions/14974394/bootstrap-datepicker-months-and-years-only for doing this with current date picker.

Also, should allow dates in the past only (but including current month).

### PR DESCRIPTION
**Pull request by justinlittman**
closes #88

### CODE REVIEW

**Comment by justinlittman** [comment]
Ahhh, it is in the package.json. I was looking for it. Removed @jcoyne .

**Comment by justinlittman** [comment]
Now it is really gone @jcoyne:
```
DN0a233061:was-registrar-app jlittman$ find app -type f | xargs grep bootstrap-datepicker
DN0a233061:was-registrar-app jlittman$ 
```

**Comment by mjgiarlo** [comment]
@jcoyne 	Can you have another look at this?

**Pull request merged**
